# Generated by Django 5.1.3 on 2024-11-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="account_id",
            new_name="reporter_account",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="report_id",
            new_name="report_owner",
        ),
    ]
