# Generated by Django 5.1.3 on 2024-11-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_account_id_report_reporter_account_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="address",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
