# Generated by Django 5.1.3 on 2024-11-27 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_account_address"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="descirption",
            new_name="description",
        ),
    ]
