# Generated by Django 5.1.3 on 2024-11-27 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_descirption_report_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="date_reported",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
