# Generated by Django 5.1.3 on 2024-11-27 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_report_date_reported"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="reporter_account",
            new_name="account",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="report_owner",
            new_name="report",
        ),
    ]
