# Generated by Django 5.1.3 on 2024-12-14 22:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_reporter_account_report_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="authority_level",
            field=models.CharField(
                choices=[
                    ("N", "None"),
                    ("L", "Logged In"),
                    ("E", "Emergency Worker"),
                    ("O", "Organizer"),
                    ("A", "Admin"),
                ],
                default="N",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("reasons", models.TextField()),
                (
                    "requested_level",
                    models.CharField(
                        choices=[
                            ("N", "None"),
                            ("L", "Logged In"),
                            ("E", "Emergency Worker"),
                            ("O", "Organizer"),
                            ("A", "Admin"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("is_approved", models.BooleanField(null=True)),
                (
                    "requestee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
