# Generated by Django 5.1.3 on 2025-01-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_task_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descirption',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
