# Generated by Django 5.1.3 on 2025-01-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_task_descirption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='descirption',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
