# Generated by Django 5.1.3 on 2025-01-15 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_account_authority_level_request'),
        ('api', '0009_alter_task_descirption'),
    ]

    operations = [
    ]
