# Generated by Django 5.2.3 on 2025-08-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_news_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='authority_level',
            field=models.CharField(choices=[('N', 'None'), ('L', 'Logged In'), ('E', 'Emergency Worker'), ('O', 'Organizer'), ('A', 'Admin')], default='L', max_length=1),
        ),
    ]
